name: Terraform Destroy

on:
  workflow_dispatch:  # Manual trigger to run when needed

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'ap-south-1'  # AWS region
      TF_VERSION: '1.9.8'       # Terraform version

    steps:
    # Step 1: Checkout GitHub repository
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v3  # Use latest version of checkout

    # Step 2: Configure AWS credentials (using aws-actions/configure-aws-credentials@v2)
    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Step 3: Verify AWS credentials are working (debugging step to ensure AWS access)
    - name: 'Verify AWS CLI'
      run: |
        aws sts get-caller-identity

    # Step 4: Set up Terraform with desired version (use hashicorp/setup-terraform@v1)
    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # Step 5: Initialize Terraform
    - name: 'Terraform Init'
      run: terraform init

    # Step 6: Validate Terraform configuration
    - name: 'Terraform Validate'
      run: terraform validate

    # Step 7: Terraform Destroy - Automatically destroy resources
    - name: 'Terraform Destroy'
      run: terraform destroy -auto-approve

