name: Terraform Destroy

on:
  workflow_dispatch: # Manual trigger

jobs:
  destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'ap-south-1'  # AWS region
      TF_VERSION: '1.9.8'       # Terraform version

    steps:
    # Step 1: Checkout the correct branch
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2
      with:
        ref: eks-modules  # Checkout the eks-modules branch

    # Step 2: Configure AWS credentials
    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Optional: Debugging step to ensure branch is correct
    - name: 'Verify Current Branch'
      run: echo "Branch: ${{ github.ref_name }}"

    # Optional: Fail if not on eks-modules branch
    - name: 'Ensure Correct Branch'
      run: |
        if [[ "${{ github.ref_name }}" != "eks-modules" ]]; then
          echo "This workflow must run on 'eks-modules' branch!"
          exit 1
        fi

    # Step 3: Set up Terraform
    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # Step 4: Destroy Terraform resources
    - name: 'Terraform Destroy'
      run: terraform destroy -auto-approve

